<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1</name>
   <tag></tag>
   <elementGuidId>1ef87957-dca6-433d-abb3-58d2e91c353b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;fdz-js-container fdz-css-container container&quot;]/div[@class=&quot;fdz-css-initial-loading-placeholder&quot;]/div[@class=&quot;fdz-css-login-page&quot;]/div[@class=&quot;fdz-css-highlight-box&quot;]/form[@class=&quot;fdz-css-login-container form&quot;]/fieldset[@class=&quot;fdz-js-login-form&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;controls input-password&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
