<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>POI_Id</name>
   <tag></tag>
   <elementGuidId>f95ea5bb-a2ea-4657-b860-0cd85101689b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody//tr[6]//td[1]//div[1]//div[2]//div[2]//div[2]</value>
   </webElementProperties>
</WebElementEntity>
