<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>POI_Name</name>
   <tag></tag>
   <elementGuidId>4f21def0-6c63-4622-a5eb-7006833d2bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody//tr[6]//td[1]//div[1]//div[2]//div[2]//div[2]</value>
   </webElementProperties>
</WebElementEntity>
