<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-tab-jobs-32</name>
   <tag></tag>
   <elementGuidId>a924f481-d870-45bb-aac0-a1015761f6e6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-tab-jobs-32</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fdz-js-lang-en-US&quot;]/div[@class=&quot;fdz-js-pulse-management fdz-css-pulse-management&quot;]/div[@class=&quot;fdz-js-pulse-container fdz-css-pulse-container interface&quot;]/div[@class=&quot;fdz-js-pulse-left-column fdz-css-pulse-left-column&quot;]/div[@class=&quot;fdz-js-menu-container fdz-css-menu-container&quot;]/ul[@class=&quot;nav builderSectionList&quot;]/li[2]/a[@class=&quot;redirect&quot;]/span[@class=&quot;menu-content&quot;]/i[@class=&quot;icon-tab-jobs-32&quot;]</value>
   </webElementProperties>
</WebElementEntity>
