<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Models</name>
   <tag></tag>
   <elementGuidId>a89fd967-443b-4a4e-b6f6-48423a45c13e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Models</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fdz-js-lang-en-US&quot;]/div[@class=&quot;fdz-js-pulse-management fdz-css-pulse-management&quot;]/div[@class=&quot;fdz-js-pulse-container fdz-css-pulse-container interface&quot;]/div[@class=&quot;fdz-js-pulse-left-column fdz-css-pulse-left-column&quot;]/div[@class=&quot;fdz-js-menu-container fdz-css-menu-container&quot;]/ul[@class=&quot;nav builderSectionList&quot;]/li[5]/a[@class=&quot;redirect&quot;]/span[@class=&quot;menu-content&quot;]/span[@class=&quot;tab-title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
