<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Finished</name>
   <tag></tag>
   <elementGuidId>05f3c277-e033-4490-ad56-bcdc6bde4a45</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Finished</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finished</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reliance&quot;)/div[1]/div[@class=&quot;fdz-js-pulse-center-column fdz-css-pulse-center-column&quot;]/div[@class=&quot;main-container fdz-js-section-view-builder-container fdz-css-section-view-builder-container&quot;]/div[@class=&quot;app-jobs-tab fdz-css-app-jobs-tab fdz-js-app-jobs-tab&quot;]/div[1]/div[@class=&quot;row-fluid&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-main&quot;]/div[@class=&quot;control-group state&quot;]/div[@class=&quot;controls&quot;]/div[@class=&quot;state fixLineHeight info-execution&quot;]/span[@class=&quot;text-success&quot;]</value>
   </webElementProperties>
</WebElementEntity>
