<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Channel_Input</name>
   <tag></tag>
   <elementGuidId>9ebc8da9-9cec-4c89-b299-f2ae6fe3de7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='s2id_fdz-form-channel']//input[1]</value>
   </webElementProperties>
</WebElementEntity>
