<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hash_Cad_Valid</name>
   <tag></tag>
   <elementGuidId>edc14178-f498-4519-989f-af94860c99d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[2]/div[3]/div/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
