<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_15.1</name>
   <tag></tag>
   <elementGuidId>78e3d264-2483-4f11-8f59-3c6ce7e6f2b1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>version</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15.1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fdz-js-lang-en-US&quot;]/div[@class=&quot;fdz-js-pulse-management fdz-css-pulse-management&quot;]/div[@class=&quot;fdz-js-pulse-header fdz-css-pulse-header&quot;]/header[@class=&quot;center-container&quot;]/div[@class=&quot;fdz-js-pulse-center-column fdz-css-pulse-center-column&quot;]/div[@class=&quot;header-logo&quot;]/a[1]/span[@class=&quot;version&quot;]</value>
   </webElementProperties>
</WebElementEntity>
