<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_excel</name>
   <tag></tag>
   <elementGuidId>a561ff00-4f5d-4d07-a3ed-b8dd24b21e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[3]/div/div[2]/div/div/table/tbody/tr[1]/td[5]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
