<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Merchant_MobileNo_Validation</name>
   <tag></tag>
   <elementGuidId>c7bf1c1a-c79a-428f-94fa-6a0fd173ae72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//html//div[4]/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//html//div[4]/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
